<?php
require_once("HARTestCase.php");

/**
 * Check custom time stamps generated by console.timeStamp() method.
 */ 
class HAR_TestEmbeddedInvalidPreview extends HAR_TestCase
{
    public function testEmbeddedInvalidPreview1()
    {
        print "\ntestEmbeddedInvalidPreview.php (1)";

        $viewer_base = $GLOBALS["harviewer_base"];
        $test_base = $GLOBALS["test_base"];

        $this->open($GLOBALS["test_base"]."tests/testEmbeddedInvalidPreview1.html");

        $document = "selenium.browserbot.getCurrentWindow().document.";

        $this->waitForCondition($document."querySelectorAll('iframe').length == 1", 10000);
        $this->waitForCondition($document."querySelector('#preview').firstChild.contentDocument.querySelectorAll('.errorTable').length == 1", 10000);

        $script1 = $document."querySelector('#preview').firstChild.contentDocument.querySelectorAll('.errorRow').length";
        $this->assertEquals("1", $this->getEval($script1));

        $script2 = $document."querySelector('#preview').firstChild.contentDocument.querySelectorAll('.errorProperty').length";
        $this->assertEquals("1", $this->getEval($script2));

        $script3 = $document."querySelector('#preview').firstChild.contentDocument.querySelectorAll('.errorMessage').length";
        $this->assertEquals("1", $this->getEval($script3));
    }

    public function testEmbeddedInvalidPreview2()
    {
        print "\ntestEmbeddedInvalidPreview.php (2)";

        $viewer_base = $GLOBALS["harviewer_base"];
        $test_base = $GLOBALS["test_base"];

        $this->open($GLOBALS["test_base"]."tests/testEmbeddedInvalidPreview2.html");

        $document = "selenium.browserbot.getCurrentWindow().document.";

        $this->waitForCondition($document."querySelectorAll('iframe').length == 1", 10000);
        $this->waitForCondition($document."querySelector('#preview').firstChild.contentDocument.querySelectorAll('.pageTable').length == 1", 10000);

        $script1 = $document."querySelector('#preview').firstChild.contentDocument.querySelectorAll('.netRow').length";
        $this->assertEquals("49", $this->getEval($script1));
    }
}
?>
