<?php
require_once("HARTestCase.php");

/**
 * Check custom time stamps generated by console.timeStamp() method.
 */ 
class HAR_TestCustomizeColumns extends HAR_TestCase
{
    public function testCustomizeColumns()
    {
        print "\nTest customize columns";

        // HAR file is specified inside the test page.
        $viewerURL = $GLOBALS["test_base"]."tests/testCustomizeColumnsPage.php";
        $harFileURL = $GLOBALS["test_base"]."tests/hars/simple.har";
        $this->open($viewerURL."?path=".$harFileURL);

        $this->waitForCondition(
            "selenium.browserbot.getCurrentWindow().document.querySelector('.PreviewTab.selected')",
            10000);

        // Make sure we are in the Preview tab.
        $this->assertElementContainsText("css=.PreviewTab.selected", "Preview");

        $document = "selenium.browserbot.getCurrentWindow().document.";

        // Test URL column (should be visible)
        $script1 = $document."querySelector('.netTable .netHrefCol').clientWidth > 0";
        $this->assertEquals("true", $this->getEval($script1));

        // Test Status column (should be hidden)
        $script2 = $document."querySelector('.netTable .netStatusCol').clientWidth == 0";
        $this->assertEquals("true", $this->getEval($script2));

        // Test Type column (should be visible)
        $script3 = $document."querySelector('.netTable .netTypeCol').clientWidth > 0";
        $this->assertEquals("true", $this->getEval($script3));

        // Test Domain column (should be visible)
        $script4 = $document."querySelector('.netTable .netDomainCol').clientWidth > 0";
        $this->assertEquals("true", $this->getEval($script4));

        // Test Size column (should be hidden)
        $script5 = $document."querySelector('.netTable .netSizeCol').clientWidth == 0";
        $this->assertEquals("true", $this->getEval($script5));

        // Test Size column (should be hidden)
        $script6 = $document."querySelector('.netTable .netTimeCol').clientWidth == 0";
        $this->assertEquals("true", $this->getEval($script6));
    }
}
?>
